### ISSUE TITLE
Is it possible to use srcset for responsive images ?

### ISSUE THREAD

**Issue by marcfilleul** [nextapps-de/spotlight#10]
Hi,

I've tried a lot of gallery/slider libraries and Spotlight could be the best I've found.

But I'm missing the capability to use srcset for the linked images.

Right now, we have to choose a unique size, which is not good with the multiple screen sizes out there.

Is there a way to use srcset or do you plan to add it ?

Thanks in advance.

**Comment by ts-thomas** [comment]
Generally it is planned to provide to something like srcset with also the logic behind to get the optimal image by:
1. current screen size
2. maximum viewport
3. pixel ratio
4. internet connection speed

I already implemented those logic for a project, because any default srcset/picture as well as its polyfills could not handle all this attributes perfectly. I need to transfer this logic into spotlight. Surely that's a good feature for the upcoming version.

**Comment by madalanagendra** [comment]
Hi ..How to give the extrenal link for the title , could you please help me, i am trying but not getting

**Comment by pryley** [comment]
@ts-thomas do you have any example or code snippets from the project you referenced about that you could share for srcset support?

**Comment by jkulhanek** [comment]
Any update on this?

**Comment by ts-thomas** [comment]
Adaptive responsive images is a part of the upcoming version :)

**Comment by ts-thomas** [comment]
"Adaptive Responsive Images" is now a core feature of Spotlight. And let me say, it is a way better than using srcset but works similar. The full documentation is on the road. Thanks for your patience.
