### ISSUE TITLE
Closing the gallery with swipe gesture or vertical scroll event

### ISSUE THREAD

**Issue by kfirba** [nextapps-de/spotlight#5]
Hey!

You've done a great job building this package!

One feature that I would love to have is the ability to close the gallery/lightbox with swipe up/down gesture (You may be familiar with this feature from Facebook - mobile) or vertical scroll with the mouse (You may be familiar with this feature from Medium).

[Example]( https://medium-zoom.francoischalifour.com/)

Do you think you can add this feature to this package?

**Comment by ts-thomas** [comment]
Yes of course. I already tried to implement it. Unfortunately, the result was not satisfactory. The problem is, the swipe direction has to be locked in one direction so that the image does not slide in both directions. This also requires a clever cooldown mechanic, because it happens quickly that the finger slips a little bit up, although you want to swipe to the left or right. I guess I can solve the problem very soon.

**Comment by kfirba** [comment]
@ts-thomas Sounds good! This feature combined with a way to use the package with a package manager (#6), will make this package probably the best "dependency-free" lightbox gallery :smile:
